### PR TITLE
MultiImage plugin edited by Eric Jeschke

### PR DESCRIPTION
**Pull request by pllim**
MultiImage plugin edited by @ejeschke, as mentioned in #32. @stscieisenhamer should test this and confirm if it is okay to merge.

### CODE REVIEW

**Comment by stscieisenhamer** [comment]
@ejeschke With latest master of ginga, I'm getting

```
No handlers could be found for logger "ginga"
Traceback (most recent call last):
  File "/Users/eisenham/anaconda/envs/stginga_py2/bin/ginga", line 4, in <module>
    __import__('pkg_resources').run_script('ginga==2.5.20151117213001', 'ginga')
  File "/Users/eisenham/anaconda/envs/stginga_py2/lib/python2.7/site-packages/setuptools-18.4-py2.7.egg/pkg_resources/__init__.py", line 735, in run_script

  File "/Users/eisenham/anaconda/envs/stginga_py2/lib/python2.7/site-packages/setuptools-18.4-py2.7.egg/pkg_resources/__init__.py", line 1652, in run_script

  File "/Users/eisenham/anaconda/envs/stginga_py2/lib/python2.7/site-packages/ginga-2.5.20151117213001-py2.7.egg/EGG-INFO/scripts/ginga", line 14, in <module>
    main.reference_viewer(sys.argv)
  File "/Users/eisenham/anaconda/envs/stginga_py2/lib/python2.7/site-packages/ginga-2.5.20151117213001-py2.7.egg/ginga/main.py", line 539, in reference_viewer
    viewer.main(options, args)
  File "/Users/eisenham/anaconda/envs/stginga_py2/lib/python2.7/site-packages/ginga-2.5.20151117213001-py2.7.egg/ginga/main.py", line 379, in main
    ginga.build_toplevel()
  File "/Users/eisenham/anaconda/envs/stginga_py2/lib/python2.7/site-packages/ginga-2.5.20151117213001-py2.7.egg/ginga/gw/GingaGw.py", line 144, in build_toplevel
    self.w.menubar = self.add_menus(menuholder)
  File "/Users/eisenham/anaconda/envs/stginga_py2/lib/python2.7/site-packages/ginga-2.5.20151117213001-py2.7.egg/ginga/gw/GingaGw.py", line 173, in add_menus
    self.w['top'].add_widget(menubar_w, stretch=0)
NameError: global name 'menubar_w' is not defined
```

**Comment by pllim** [comment]
@stscieisenhamer , I don't get any error like that when I start Ginga (not `stginga`). Did you do `git clean -xdf` before you rebuild?

**Comment by stscieisenhamer** [comment]
I did better: wiped out the whole directory. There seems to be a basic edit that fixes it for me: menubar_w -> menubar. I'm testing now. There is no other reference to menubar_w anywhere.

**Comment by stscieisenhamer** [comment]
You may not see it because its in a OS X check, if you are not running under OS X.

**Comment by pllim** [comment]
Ah, yes. I just noticed that.

``` python
        if len(macos_ver) > 0:
            self.w['top'].add_widget(menubar_w, stretch=0)
        else:
            holder.add_widget(menubar, stretch=1)
```

Yes, looks like a bug on the Ginga side. Are you going to file a PR there?

**Comment by stscieisenhamer** [comment]
Yep.

And, with a temporary fix to get ginga to run, these changes are good.

**Comment by pllim** [comment]
Tried to give @ejeschke the proper credit for #50 via #51 but it doesn't quite work. Ah, well! :frowning:

**Pull request merged**
