### PR TITLE
Track upstream changes in Ginga

### PR DESCRIPTION
**Pull request by ejeschke**
- this modifies MIPick to work with some changes in plotting wrappers in upstream Ginga

### CODE REVIEW

**Comment by ejeschke** [comment]
Ping @pllim, @stscieisenhamer

**Comment by pllim** [comment]
@stscieisenhamer , okay to merge?

**Comment by stscieisenhamer** [comment]
yes

sorry, too many interrupts generated the last few weeks.

**Comment by pllim** [comment]
No problem. Thanks!

**Pull request merged**
