### PR TITLE
Fixes for upstream changes to colorbar and readout handling

### PR DESCRIPTION
**Pull request by ejeschke**
This fixes the layout of stginga to handle changes in the way the color bar and readout are handled upstream.  You now have more flexibility if you want to lay them out differently or customize further.

### CODE REVIEW

**Comment by pllim** [comment]
Since `MultiImage` uses the custom layout, I'll let @stscieisenhamer merge if he is okay with it.

**Comment by pllim** [comment]
Actually, I think I am just going to merge, because I need this fix to test my own PR.

**Comment by pllim** [comment]
Thanks, @ejeschke !

**Comment by stscieisenhamer** [comment]
Will look, but don't see why this would be an issue.

**Pull request merged**
