### PR TITLE
Populate ipynb docs

### LINKED ISSUE #56: Document usage with IPython Notebook
Populate `docs/source/ipynb.rst` with contents of the Sprint demo after #55 is merged.

### PR DESCRIPTION
**Pull request by eteq**
This should close #56 by populating the docs with info about the interactive notebook usage.

Note this also does some re-organization by removing the "examples" folder, dropping the config stuff into "data" and the notebook examples into the docs.  That was the easiest way to make it so that I could embed the notebooks in the sphinx docs.

cc @stscieisenhamer

### CODE REVIEW

**Comment by pllim** [comment]
I am against moving `*.cfg` away from `examples/configs` folder. This is because there is where Ginga store its example config files. Ginga users would look there first if they are familiar with Ginga's organization. Can we please keep the `*.cfg` files where they are?

**Comment by eteq** [comment]
Oh, I didn't realize this was parallel structure to `ginga`, @pllim .  TBH I don't think too many users know about that, but I see your point that the parallel structure might be helpful.  So the commit I just pushed up puts them back and only moves the notebook.

**Comment by pllim** [comment]
Thanks for your understanding, @eteq . Could you please squash the commits? This would make rebasing #61 easier, so it won't be confused by the reorganization and the undoing of it.

**Comment by eteq** [comment]
@pllim - OK, done - will that work for you?

**Comment by pllim** [comment]
@eteq , I still see the original commits, not the squashed one. Did you push it to the repo?

**Comment by pllim** [comment]
Ah, okay. I think I misunderstood. They look fine. Merging. Thanks!

**Pull request merged**
